# Generated by Django 4.2.2 on 2023-06-21 10:35

import django.core.validators
from django.db import migrations, models
import my_music_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(max_length=15, validators=[django.core.validators.MinLengthValidator(2), my_music_app.web.validators.TextContainOnlyAlphaNumericAndUnderscoreValidator]),
        ),
    ]
