# Generated by Django 4.2.2 on 2023-06-23 22:09

import django.core.validators
from django.db import migrations, models
import plants_exam.plants.validators


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), plants_exam.plants.validators.plant_name_only_letters]),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='last_name',
            field=models.CharField(max_length=20, validators=[plants_exam.plants.validators.check_name_capital_latter]),
        ),
    ]
